### ISSUE TITLE
No collections requirements file found

### ISSUE THREAD

**Issue by kirolous** [ansible-semaphore/semaphore#1144] opened 2023-01-12 18:47 UTC
![image](https://user-images.githubusercontent.com/10713102/212152915-6d587709-d8cb-44eb-85f4-cfe0b6d5201b.png)

File exists, however semaphore cant seem to find  it

**Comment by kirolous** [comment] 2023-01-12 18:48
on version 2.8.77
![image](https://user-images.githubusercontent.com/10713102/212153243-d83117e7-2196-41a3-9a9e-1638e82be54b.png)

**Comment by jp1337** [comment] 2023-02-01 16:36
I have the same problem since the update today. The reading of the Collections path has been changed. It is no longer searched globally for collections/requirements.yml, but in the folder where the playbook is located.

In my case this gives a big chaos, because I have structured my playbooks cleanly in folders and now I have to create many collections/requirements.txt files.

```
Example:
playbooks
├── linux
│   ├── xxx
│   │   ├── collections
│   │   │   ├── requirements.yml
│   ├── yyy
│   │   ├── collections
│   │   │   ├── requirements.yml
│   ├── zzz
│   │   ├── collections
│   │   │   ├── requirements.yml
```

Sure, the advantage is that you only have to install the Collections that are also needed for this Playbook. For larger projects, however, it is total chaos.

**Comment by nlvw** [comment] 2023-04-20 21:11
The problem is here:
https://github.com/ansible-semaphore/semaphore/blob/864d8bd8aa5d55f334a9ae4f3c52aa44667a65ac/services/tasks/runner.go#L508

Whereas Roles looks like:
https://github.com/ansible-semaphore/semaphore/blob/864d8bd8aa5d55f334a9ae4f3c52aa44667a65ac/services/tasks/runner.go#L537

The role implementation does this correctly and the collections implementation should be changed to look at the base of the project/repository then 'collections/requirements.yml'.

**Comment by nlvw** [comment] 2023-04-20 21:34
> I have the same problem since the update today. The reading of the Collections path has been changed. It is no longer searched globally for collections/requirements.yml, but in the folder where the playbook is located.
> 
> In my case this gives a big chaos, because I have structured my playbooks cleanly in folders and now I have to create many collections/requirements.txt files.
> 
> ```
> Example:
> playbooks
> ├── linux
> │   ├── xxx
> │   │   ├── collections
> │   │   │   ├── requirements.yml
> │   ├── yyy
> │   │   ├── collections
> │   │   │   ├── requirements.yml
> │   ├── zzz
> │   │   ├── collections
> │   │   │   ├── requirements.yml
> ```
> 
> Sure, the advantage is that you only have to install the Collections that are also needed for this Playbook. For larger projects, however, it is total chaos.

Until this is fixed my current workaround is to create symlinks that point to `roles/requirements.yml`.  So each of my playbook directories have a 'collections' folder which contains said symlink.  Even my `collections/requirements.yml` file is a symlink to `roles/requirements.yml`.  Ansible galaxy allows you to define both roles and collections in a single file which is nice.

**Comment by Ye-Min-Tun** [comment] 2023-05-03 09:05
Any workaround? I also faced the same issues.

**Comment by Ye-Min-Tun** [comment] 2023-05-03 09:33
> > I have the same problem since the update today. The reading of the Collections path has been changed. It is no longer searched globally for collections/requirements.yml, but in the folder where the playbook is located.
> > In my case this gives a big chaos, because I have structured my playbooks cleanly in folders and now I have to create many collections/requirements.txt files.
> > ```
> > Example:
> > playbooks
> > ├── linux
> > │   ├── xxx
> > │   │   ├── collections
> > │   │   │   ├── requirements.yml
> > │   ├── yyy
> > │   │   ├── collections
> > │   │   │   ├── requirements.yml
> > │   ├── zzz
> > │   │   ├── collections
> > │   │   │   ├── requirements.yml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sure, the advantage is that you only have to install the Collections that are also needed for this Playbook. For larger projects, however, it is total chaos.
> 
> Until this is fixed my current workaround is to create symlinks that point to `roles/requirements.yml`. So each of my playbook directories have a 'collections' folder which contains said symlink. Even my `collections/requirements.yml` file is a symlink to `roles/requirements.yml`. Ansible galaxy allows you to define both roles and collections in a single file which is nice.

This still doesn't work for me.

**Comment by andreas-marschke** [comment] 2023-05-25 00:36
@Ye-Min-Tun FWIW I've implemented something similar in my MR to resolve this issue. 
Please review/test it and see if it works for you
https://github.com/ansible-semaphore/semaphore/pull/1240

**Comment by Ye-Min-Tun** [comment] 2023-05-25 01:23
@andreas-marschke Sure sir. I resolved this by adding a requirement.yml file inside collection directory. 
Note: earlier I think yml and yaml are the same. Semaphore only look for yml, not yaml. That spent my half a day.

**Comment by pydlv** [comment] 2023-05-26 02:23
big issue causing me much pain please fix

**Comment by Ye-Min-Tun** [comment] 2023-05-26 03:20
@pydlv  You just need to add requirements.yml file (with the collections you need to install) under the collections directory of your workspace.

**Comment by guard43ru** [comment] 2023-05-29 15:23
At now (in 2.8.90) "right path" is
`requirementsFilePath := path.Join(t.getPlaybookDir(), "collections", "requirements.yml")`

In my project tree it looks as:
```
├── ansible.cfg
├── collections
│   └── requirements.yml (original file)
├── playbooks
│   ├── one.yml
│   ├── two.yml
│   └── collections
│       └── requirements.yml -> ../../collections/requirements.yml (hot fix symlink)
└── roles
    ├── one
    └── two
```

I think was best solution search requirements.yml in all popular places:
```
/requirements.yml (root project dir)
/collections/requirements.yml
/[getPlaybookDir]/collections/requirements.yml
```

**Comment by alexbarton** [comment] 2023-05-29 18:27
Fully agree!

But probably reverse the order, and use the first one found ("most specific one")?

**Comment by rwaffen** [comment] 2023-09-14 08:53
just for the record: i'm working around this like this. 
so i can include it in all my playbooks which need some collections.

```
---
# playbooks/test_play.yml
- name: "ダミープラグ on localhost"
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: "Install ansible collections"
      ansible.builtin.include_tasks:
        file: "../tasks/install_collections.yml"

---
# tasks/install_collections.yml
- name: Install collections
  ansible.builtin.command: "ansible-galaxy collection install -r ../collections/requirements.yml"
  register: collections_install
  changed_when: collections_install.rc != 0

```

**Comment by RusticPotatoes** [comment] 2023-12-02 00:54
> Any workaround? I also faced the same issues.

yea you would need to put a collections/requirements.yml folder in the same path where the playbook you are running is.

**Comment by jp1337** [comment] 2024-06-17 09:52
This is resolved with version [v2.9.109](https://github.com/semaphoreui/semaphore/releases/tag/v2.9.109)
I think the issue can be closed.

**Closed as completed** 2024-06-18 17:20 UTC

**Comment by deadnews** [comment] 2024-07-31 08:50
> I think was best solution search requirements.yml in all popular places:
> 
> ```
> /requirements.yml (root project dir)
> ```

Why is `/requirements.yml (root project dir)` not installing?

https://github.com/semaphoreui/semaphore/blob/550c2a54315c85be0ad08ef6940dd20e3d2a6b3f/db_lib/AnsibleApp.go#L128-L144

**Comment by alexbarton** [comment] 2024-07-31 19:30
@DeadNews, the root folder doesn't work for me either ... but I guess this is covered in #1240?
