### ISSUE TITLE
Api endpoints extra parameters

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#463] opened 2018-02-16 19:26 UTC
arising from #190 it would be good if we could POST the same options to the api to start a task that are available from the interface (environment etc....)

**Comment by kumy** [comment] 2019-11-21 13:19
We are also interested in passing dynamically `Extra CLI arguments` to the `post /project/{project_id}/tasks ` endpoint.

**Comment by kumy** [comment] 2019-11-21 15:32
As a workaround I've used the `put /project/{project_id}/templates/{template_id}` endpoint to update the `Extra CLI arguments` before launching the task…

**Comment by lennart** [comment] 2021-11-01 19:23
I had been using the api to start a job in v2.6.8 with exactly the mentioned functionality:

with new_task.json being:

```json5
{
  "template_id": 1,
  "debug": false,
  "dry_run": false,
  "arguments": "[\"--extra-vars\", \"foo_arg=bar baz_arg=qux\"]"
}
```

then ran:

```
cat << EOF > semaphore_api_headers
Content-Type: application/json
Accept: application/json
Authorization: Bearer ${SEMAPHORE_DEPLOY_TOKEN}
EOF
curl --verbose --fail --show-error --header @semaphore_api_headers -d@new_task.json ${SEMAPHORE_PROJECT_URL}/tasks
```

and this functionality (`"arguments": "[\"--extra-vars\" ...]"`) is now missing in 2.8.9 and I could not find any note of breaking (api) changes.
What was the reason this was removed and more importantly, how can we get it back?

I'll read the code and try to figure out how to restore this functionality (I'd call this regression)

I would agree that the approach described above is somewhat clunky and it might be nicer to specify extra-args as JSON directly.

**Comment by lennart** [comment] 2021-11-01 21:00
ok, as far as I understand, this now goes into the `environment` key, see: https://github.com/ansible-semaphore/semaphore/issues/767

**Comment by lennart** [comment] 2021-11-01 22:14
however, with the former usage via `arguments` I could still use a defined environment in the task template and have the `arguments` be merged with this. the _new_ version completely overrides any configure environment of the task template, i.e. I have to pass in all variables on task invocation, whereas before I only had to pass in those that need to be overriden/vary between job runs.

Is there a way to achieve the _merging_ of environments/extra-vars like before?

**Comment by fiftin** [comment] 2021-11-01 22:36
Hi @lennart ,

Yes, you are right, environments must be merged. It will be implemented ASAP.

**Comment by lennart** [comment] 2021-11-02 07:10
Hi @fiftin,

great, thanks!

**Comment by fiftin** [comment] 2022-01-27 16:49
All done.

**Closed by fiftin** 2022-01-27 16:49 UTC
