### ISSUE TITLE
Install without docker, boot at start up

### ISSUE THREAD

**Issue by ly2ly** [ansible-semaphore/semaphore#247] opened 2017-01-21 17:33 UTC
Hello,

I try semaphore. I do install without docker on a debian 8 cloud server. All installation process run without problem. But I have problem to create file to launch semaphore at server start up.
I create 2 files: 
- semaphore.sh at /usr/bin with
#!/bin/sh -
nohup /usr/bin/semaphore -config /home/ansible/semaphore_config.json &

- semaphore.service
[Unit]
Description=Semaphore for web ansible management
After=mysqld.service

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/bin/semaphore.sh

TimeoutStopSec=60

[Install]
WantedBy=multi-user.target

I had second file in systemctl.

So after I can start semaphore using service but It can't init on start up.
So I forgot something? Or have you any kind of startup files?

Thanks

**Comment by kpashka** [comment] 2017-02-09 08:04
@ly2ly Try running it without `nohup` in your shell script, just like this:
`/usr/bin/semaphore -config /home/ansible/semaphore_config.json`

Also if you add this lines to `[Service]` section of systemd config and you'll be able to view application logs via `journalctl -u semaphore`:

```
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=semaphore
```

**Comment by strangeman** [comment] 2017-02-22 09:37
My systemd unit:

```
[Unit]
Description=Semaphore Ansible Web Interface
After=network.target
Requires=network.target

[Service]
User=ansible
Group=ansible
ExecStart=/opt/semaphore/semaphore -config /opt/semaphore/semaphore_config.json
WorkingDirectory=/opt/semaphore
Restart=on-failure
RestartSec=100ms
StartLimitBurst=5
StartLimitInterval=300

[Install]
WantedBy=multi-user.target
```

**Comment by ly2ly** [comment] 2017-02-22 19:40
Hello thanks for your help but I try to adapt to my case, I can launch It manually but it don't work on start, what is the problem?

[Unit]
Description=Semaphore Ansible Web Interface
After=network.target
Requires=network.target

[Service]
User=ansible
Group=ansible
ExecStart=/usr/bin/semaphore -config /home/ansible/semaphore_config.json
WorkingDirectory=/usr/bin/
Restart=on-failure
RestartSec=100ms
StartLimitBurst=5
StartLimitInterval=300

[Install]
WantedBy=multi-user.target

**Comment by matejkramny** [comment] 2017-02-22 20:08
Should check out the boot log or `systemd` logs to find out why it's not launching

**Comment by strangeman** [comment] 2017-02-22 23:08
Run `journalctl -u semaphore` to get the logs.

чт, 23 февр. 2017 г., 6:08 Matej Kramny <notifications@github.com>:

**Comment by laeshiny** [comment] 2017-03-25 22:05
You might skip this command
"""sudo systemctl enable semaphore.service"""

**Comment by resetnow** [comment] 2017-05-15 11:26
I'm having the same problem. What's weird is that according to system journal it appears to start up, but then it exits with error:

```
● ansible-semaphore.service - Ansible Semaphore
   Loaded: loaded (/etc/systemd/system/ansible-semaphore.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-05-15 14:25:41 MSK; 28s ago
  Process: 957 ExecStart=/opt/semaphore/semaphore -config /opt/semaphore/semaphore_config.json (code=exited, status=2)
 Main PID: 957 (code=exited, status=2)

May 15 14:25:40 ubuntu-jenkins systemd[1]: Started Ansible Semaphore.
May 15 14:25:41 ubuntu-jenkins semaphore[957]: Semaphore 2.3.0
May 15 14:25:41 ubuntu-jenkins semaphore[957]: Port :3000
May 15 14:25:41 ubuntu-jenkins semaphore[957]: MySQL ansible@127.0.0.1:3306 semaphore
May 15 14:25:41 ubuntu-jenkins semaphore[957]: Tmp Path (projects home) /opt/semaphore/semaphore_data
May 15 14:25:41 ubuntu-jenkins systemd[1]: ansible-semaphore.service: Main process exited, code=exited, status=2/INVAL
May 15 14:25:41 ubuntu-jenkins systemd[1]: ansible-semaphore.service: Unit entered failed state.
May 15 14:25:41 ubuntu-jenkins systemd[1]: ansible-semaphore.service: Failed with result 'exit-code'.
```

**Comment by twhiston** [comment] 2018-02-16 20:12
cant reproduce and closing due to age

**Closed by twhiston** 2018-02-16 20:12 UTC
