### ISSUE TITLE
So does this support LDAPS or not?

### ISSUE THREAD

**Issue by KenK73** [ansible-semaphore/semaphore#756] opened 2021-10-09 09:41 UTC
I see there is an "ldap_needtls" boolean in the config, but I cant find any mention of how to make it work.  My Semaphore works fine under normal LDAP, but where I want to use it, straight LDAP is not permitted and LDAPS must be used.

If I add the "needtls: true" and change the port to 636, I get this error in the log when attempting to log in:

`Checking DB migrations`
`MySQL root@172.17.0.2:3306 semaphore`
`Tmp Path (projects home) /tmp/semaphore`
`Semaphore v2.7.22`
`Interface`
`Port :3000`
`Server is running`
`INFO[0013] unable to read LDAP response packet: read tcp 172.17.0.11:34666->10.0.30.135:636: read: connection reset by peer`

This is a docker container, so I copied my root/intermediate CA certs into /etc/ssl/certs/ca-certificates.crt but that had no impact.

**Comment by fiftin** [comment] 2021-10-11 17:49
I adding support LDAPS but I need help with testing.
I will create pre-release soon.

**Comment by KenK73** [comment] 2021-10-12 02:09
Thanks!  I will assist in the testing as best I can.

**Comment by Bkbest** [comment] 2021-10-13 04:18
Hi @fiftin, I will also test this.

**Comment by fiftin** [comment] 2021-10-17 08:15
Hi @KenK73, @Bkbest
Please try v2.8.0: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.0

You need to set flag `ldap_needtls: true` in config file before.

**Comment by KenK73** [comment] 2021-10-18 00:51
I am getting this error now:

Semaphore v2.8.0
Interface
Port :3000
Server is running
INFO[0023] LDAP Result Code 200 "Network Error": ldap: already encrypted
INFO[0973] LDAP Result Code 200 "Network Error": ldap: already encrypted

Here are my ldaps settings:

        "ldap_needtls": true,
        "ldap_binddn": "cn=svc.bind.semaphore,ou=service,ou=users,ou=test,dc=test,dc=lab",
        "ldap_bindpassword": "password",
        "ldap_server": "mad01.test.lab:636",
        "ldap_searchdn": "ou=users,ou=test,dc=test,dc=lab",
        "ldap_searchfilter": "(&(objectCategory=Person)(sAMAccountName=%s))",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "sAMAccountName",
                "cn": "cn"
        },
        "ldap_enable": true,

If I change the above to "ldap_needtls: false" and set the server port to 389, it works fine with just those 2 changes.

**Comment by emollusion** [comment] 2021-10-21 09:39
Hi!

I have tried to configure LDAPS and run in to this problem.

From semaphore, running both against a LDAP Proxy and against an AD server, are logs:
```
Semaphore:
AD: Oct 21 09:26:02 **** semaphore[1714042]: time="2021-10-21T09:26:02Z" level=info msg="unable to read LDAP response packet: read tcp ****:56684->****:636: read: connect
ion reset by peer"
LDAP Proxy: Oct 21 09:27:45 **** semaphore[1714106]: time="2021-10-21T09:27:45Z" level=info msg="unable to read LDAP response packet: unexpected EOF"
```

From the LDAP Proxy, I get this error:
```
2021-10-21T09:27:45.094584+0000 [****#info] The downstream application and the Authentication Proxy were not able to establish an SSL connection. It is possible this is because of a TLS protocol mismatch. Your configured minimum_tls_version is SSLv3. The negotiated TLS version is <Unknown>. The minimum_tls_version currently allowed MAY be higher than your application can support. Please look into setting the `minimum_tls_version` option in your [ldap_server_auto] section if you need to use a lower version of the TLS Protocol. Error message: [('SSL routines', 'SSL23_GET_CLIENT_HELLO', 'unknown protocol')].
```

The config is altered to use port 636 instead of 389, and ldap_needtls is set to true.

Hope this is a step forward in testing this :)

**Comment by tiny-pangolin** [comment] 2021-11-12 18:29
I am experiencing similar issues. Monday I had a tech not able to login using FreeIPA as the source for auth. previously we wereable to have TLS enabled on port 389. We have tested both of our serves on port 389 and 686 and are receiving the following errors in our error logs. everything works fine if I set 

port 686: LDAP Result Code 200 \"Network Error\": dial tcp 192.168.XXX.XXX:686: connect: no route to
host

port 389: evel=info msg="LDAP Result Code 200 \"Network Error\

**Comment by KenK73** [comment] 2021-11-13 03:33
I just tested again with v2.8.21 and I am still unable to use LDAPS.  The standard LDAP works fine.

INFO[0121] LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839

Same servers and same bind account that works for LDAP, so this is TLS related.  DC's certs are signed by a custom CA, so maybe I need to put root/intermediate certs somewhere in this docker container?

**Comment by srinathman** [comment] 2022-01-27 21:15
Does it support LDAPS (port 636) or LDAP+StartTLS (port 389) ?

I'm trying LDAPS and I get 
`time="2022-01-27T21:14:57Z" level=info msg="LDAP Result Code 200 \"Network Error\": ldap: already encrypted"
`

**Comment by fiftin** [comment] 2022-02-03 22:50
Hi @srinathman,

I have no experience with LDAP. I need help with it. 

Theoretically it should works if config flag `ldap_needtls` is raised.

But I can't check it.

I found similar issue https://github.com/shaj13/go-guardian/issues/97

**Comment by KenK73** [comment] 2022-02-03 23:29
I have no problem getting LDAP working, LDAPS on the other hand, I was getting the "already encrypted" error.  I have not tried anything recently.

**Comment by srinathman** [comment] 2022-02-04 01:04
Hi @fiftin ,
I'm not fluent in go, but checking the go-ldap code I belive that you need to use the recommended  "DialURL" function instead of Dial or DialTLS. It looks like DialURL will take care of using the correct protocol according to the url prefix and opts (ldap, ldaps, ldap+tls, etc).

Ref: https://github.com/go-ldap/ldap/blob/13008e4c5260d08625b65eb1f172ae909152b751/conn.go#L205

I can help testing if needed.

**Comment by fiftin** [comment] 2022-02-04 09:24
@srinathman, you are right, I will changed it. Old variant deprecated, but it should works.

**Comment by fiftin** [comment] 2022-02-04 11:41
I updated ldap library, may it fix issue.

https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.43

**Comment by KenK73** [comment] 2022-02-04 19:44
Running 2.8.43 now and still having LDAPS issues. I setup for port 389/no TLS and it works fine. If I setup on port 636 with TLS I get "LDAP Result Code 200 Network Error LDAP already encrypted" and if I try port 636 without TLS I get "connection reset by peer".

I am using a private CA and I am not sure where I would need to add the PEM file for that on the Semaphore container if that might be my issue.

**Comment by srinathman** [comment] 2022-02-04 22:29
@fiftin  please check the following pull request:  https://github.com/ansible-semaphore/semaphore/pull/854
I believe it fixes most of the ldap related issues discussed here.

**Comment by Driaan** [comment] 2022-02-09 10:48
Same issue hopefully this gets merged and released quickly..

**Comment by fiftin** [comment] 2022-02-10 14:35
Please try this version: https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.50

**Comment by Driaan** [comment] 2022-02-10 15:07
Thanks @fiftin this seems to be working! 

Using these settings
`"ldap_enable": true`
`"ldap_needtls": true`

**Comment by fiftin** [comment] 2022-02-10 18:41
@KenK73 , can you confirm LDAPS works?

**Comment by tiny-pangolin** [comment] 2022-02-10 20:23
I changed to using port 636, set ```ldap_needtls: true``` and was able to sign in on both of my semaphore instances run 2.8.50

**Comment by KenK73** [comment] 2022-02-10 21:25
Two thumbs up!  The log message still says LDAP and not LDAPS, but it did work with TLS true and on port 636 with v2.8.50.

**Closed as completed** 2022-02-12 08:12 UTC
Labels: bug

**Comment by venkatasankhya** [comment] 2022-02-16 10:31
I have tested LDAPS using v2.8.50 and still see LDAP Results Code 200 error.

Request failed with status code 500 on Semaphore UI

Logs:
Starting Semaphore Ansible UI...
MySQL root@127.0.0.1:3306 semaphore
Tmp Path (projects home) /mnt/xvda/semaphore
Semaphore v2.8.50
Interface
Port :3000
Server is running
time="2022-02-16T10:15:51Z" level=info msg="LDAP Result Code 200 \"Network Error\": dial tcp: address ldaps://ldap.pc.test...in address"
time="2022-02-16T10:16:28Z" level=info msg="LDAP Result Code 200 \"Network Error\": dial tcp: address ldaps://ldap.pc.test...in address"
time="2022-02-16T10:16:45Z" level=info msg="LDAP Result Code 200 \"Network Error\": dial tcp: address ldaps://ldap.pc.test...in address"

config.json:

"ldap_binddn": "CN=ldapuser,OU=Service Accounts,OU=Servers,DC=pc,DC=testsrver,DC=com",
        "ldap_bindpassword": "password",
        "ldap_server": "ldaps://testserver.com:636",
        "ldap_searchdn": "DC=testserver,DC=com",
        "ldap_searchfilter": "(&(objectCategory=Person)(sAMAccountName=%s))",
        "ldap_mappings": {
                "dn": "distinguishedName",
                "mail": "userPrincipalName",
                "uid": "sAMAccountName",
                "cn": "cn"
        },
        "telegram_chat": "",
        "telegram_token": "",
        "concurrency_mode": "",
        "max_parallel_tasks": 0,
        "email_alert": false,
        "telegram_alert": false,
        "ldap_enable": true,
        "ldap_needtls": true,

**Comment by KenK73** [comment] 2022-02-16 16:09
Don't put the ldaps:// on the server, just use IP/FQDN:port

**Comment by venkatasankhya** [comment] 2022-02-17 10:49
that fixed the issue. Thank you for your help.

**Comment by beKGB** [comment] 2023-09-28 05:50
I have a semaphore container running through docker compose

I configured ldap on port 389 and everything works (but my organization does not agree to this type of connection), I switched to port 636 and it doesn't work (I checked with true and false set in the ldap_needtls property), the message I receive is:

"unable to read LDAP response packet: read tcp semaphore_container_ip:38032->ldap_ip:636: read: connection reset by peer"

and there are no logs from the communication attempt on the ldap server (but they were there when I connected via port 636)

I suspect that I need to add a trusted ca cert to the semaphore container, but after mounting it to the "etc/ssl/certs" path, nothing helped (I copied it from the server and it is correct). openssl , update-ca-trust extract , ldapsearchl or dapwhoami commands do not work on the container.

Installing anything on this container is also not possible because only the shell is available: "busybox sh", but within it you do not have permission to call, for example, the apk.

I am asking for help urgently

**Comment by KenK73** [comment] 2023-09-28 07:06
Mine didnt start working until I got to v2.8.89

I am using the semaphore/semaphore:latest image but have not updated in awhile.

I dont see anywhere that I messed with the certs file, which is surprising, but its working.


#!/usr/bin/bash
docker run -d  \
   --expose 3000 \
   --restart always \
   --name semaphore \
   --link semaphore-mysql:mysql \
   -v /mnt/containers/semaphore/config.json:/etc/semaphore/config.json \
   -v /mnt/containers/semaphore/tmp/semaphore:/tmp/semaphore \
   semaphoreui/semaphore:latest \
   semaphore server --config /etc/semaphore/config.json

# Add modules
docker exec -t semaphore ansible-galaxy collection install \
  ansible.windows \
  community.vmware \
  community.general 



From my config:

        "ldap_binddn": "cn=svc.bind.semaphore,ou=service,ou=users,dc=my,dc=lab",
        "ldap_bindpassword": “pa$$word",
        "ldap_server": “labad01.my.lab:636",
        "ldap_searchdn": "ou=users,dc=my,dc=lab",
        "ldap_searchfilter": "(&(objectCategory=Person)(sAMAccountName=%s))",
        "ldap_mappings": {
                "dn": "dn",
                "mail": "mail",
                "uid": "sAMAccountName",
                "cn": "cn"
        },


Hope that helps.

**Comment by beKGB** [comment] 2023-10-02 14:39
i have semaphore with v2.9.35, and it still doesn't work for me... I don't know what to do, my ldap config:
````
 	"ldap_enable": true,
 	"ldap_binddn": "cn=admin,ou=harbor,dc=xx,dc=xxx,dc=com",
 	"ldap_bindpassword": "passwd",
 	"ldap_server": "myLdap.com:636",
 	"ldap_searchdn": "ou=harbor,dc=xx,dc=xxx,dc=com",
        "ldap_searchfilter": "",
 	"ldap_mappings": {
 		"dn": "dn",
 		"mail": "mail",
 		"uid": "sAMAccountName",
 		"cn": "cn"
 	},
 	"ldap_needtls": true,
```
I have a docker container with harbor (goharbor.io) on the same machine and everything works with the same settings, 

I think the problem is with the place where ca_bundle.crt is mounted or if semaphore is not prepared for it, then:
maybe it is possible to disable certificate verification of the LDAP server it connects to?

**Comment by KenK73** [comment] 2023-10-02 17:30
I think LDAPS without certs is just LDAP on port 389.  Not sure how you would get LDAPS to behave like that.

**Comment by beKGB** [comment] 2023-10-03 05:44
LDAP on port 389 and then user passwords sent to the LDAP server are visible in plaintext during network transmission.

2.8.65 works .....
well, I'll look for a higher version that works too

**Comment by bioszombie** [comment] 2023-12-27 16:21
image: semaphoreui/semaphore:latest
SEMAPHORE_LDAP_ACTIVATED: 'yes'
SEMAPHORE_LDAP_PORT: '636'
SEMAPHORE_LDAP_NEEDTLS: 'yes'

Request failed with status code 500 

time="2023-12-27T16:12:41Z" level=warning msg="unable to read LDAP response packet: unexpected EOF"

"ldap_enable": true,
"ldap_needtls": true,


I'm not sure what I'm doing wrong but I can't get this to work.

**Comment by dc-jbd** [comment] 2023-12-27 16:45
I had it working a while ago using ldaps on AD with this snippet in my config:

"ldap_enable": true,
 	"ldap_needtls": true,
 	"ldap_binddn": "cn=ro-account,ou=service accounts,blah blah blah",
 	"ldap_bindpassword": "blahblahblah",
 	"ldap_server": "yourfavADserver.example.com:636",
 	"ldap_searchdn": "OU=T1-group,OU=Admin,blahDCblahblah",
 	"ldap_searchfilter": "(&(sAMAccountName=%s)(memberOf=CN=T1_Ansible_Admins,OU=Role Groups,OU=T1,OU=Admin,blahDCblahblah))",
 	"ldap_mappings": {
 		"dn": "distinguishedName",
 		"mail": "userPrincipalName",
 		"uid": "sAMAccountName",
 		"cn": "cn"
 	},

Change the dn and filter to your FQDN stuff in AD accordingly. We use an internal singing CA and push out the CA chain everywhere.

If anyone is going to post that it doesn't work - you need to include your ldap config in the post or you aren't going to get the help you need.

**Comment by bioszombie** [comment] 2023-12-27 16:48
> I had it working a while ago using ldaps on AD with this snippet in my config:
> 
> "ldap_enable": true, "ldap_needtls": true, "ldap_binddn": "cn=ro-account,ou=service accounts,blah blah blah", "ldap_bindpassword": "blahblahblah", "ldap_server": "yourfavADserver.example.com:636", "ldap_searchdn": "OU=T1-group,OU=Admin,blahDCblahblah", "ldap_searchfilter": "(&(sAMAccountName=%s)(memberOf=CN=T1_Ansible_Admins,OU=Role Groups,OU=T1,OU=Admin,blahDCblahblah))", "ldap_mappings": { "dn": "distinguishedName", "mail": "userPrincipalName", "uid": "sAMAccountName", "cn": "cn" },
> 
> Change the dn and filter to your FQDN stuff in AD accordingly. We use an internal singing CA and push out the CA chain everywhere.

I authenticate against a LDAP server out of Authentik. Its not a WindowsAD. The SSL cert is installed on the host.

**Comment by dc-jbd** [comment] 2023-12-27 16:53
@bioszombie in most cases ldap is ldap (outside of how the tree is structured anyway). If you aren't getting what you expect with the bind, search and filters you chose then those might be your problem. Use command line ldapsearch to figure out if you are even close with your binding, dn and search filters. Once you get ldapsearch to return what you want then fix your semaphore config. If you can't get ldapsearch to work, then semaphore with your ldap config will never work.

NOTE - I'd love to see more debugging for this and other stuff in Semaphore but we don't have that right now. You have to use something like ldapsearch to fine tune what you want and plug that data into your config
