### ISSUE TITLE
If Semaphore is served https, external fonts should use https too.

### ISSUE THREAD

**Issue by Ranzear** [ansible-semaphore/semaphore#530] opened 2018-04-24 16:54 UTC
Mixed content warnings in Chrome regarding font links:

http://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf

Semaphore's pages need to use https protocol if hosted with https protocol.

**Comment by fiftin** [comment] 2018-05-04 09:27
@twhiston Did you reproduce this bug?

**Comment by twhiston** [comment] 2018-05-07 10:07
@fiftin - I havn't had time to try yet tbh as I was at KubeCon last week. I'll try and reproduce it this week

**Comment by matejkramny** [comment] 2019-07-11 01:20
Seems to be fixed with 01a0ec271fea5e075dc72826137f3dd9fa5f50d1

**Closed by matejkramny** 2019-07-11 01:20 UTC
Labels: bug
