### ISSUE TITLE
Problem Cookie Reverse Proxy

### ISSUE THREAD

**Issue by albruz** [ansible-semaphore/semaphore#239] opened 2016-12-14 14:46 UTC
Hello! I set up an apache reverse proxy to secure Semaphore but when I try to log in it keeps me in the login page even if it was succesfull..i think it could be a problem with the cookie but i can't figure out a solution..any ideas?

**Comment by matejkramny** [comment] 2016-12-15 05:31
Look for the cookie it is sending (if any). Could be domain/expiry of the cookie being sent or the reverse proxy ignoring the cookie header.

**Comment by rakshazi** [comment] 2016-12-15 07:06
Possibly duplicate of #193

**Closed** 2016-12-21 08:55 UTC
