### ISSUE TITLE
Answer file for semaphore -setup?

### ISSUE THREAD

**Issue by KarenTovmasian** [ansible-semaphore/semaphore#218] opened 2016-11-10 11:53 UTC
Hi guys!

First of all, thanks you for a great solution for ansible fans.
We want to automate semaphore setup so it meets or Infrastructure-As-Code requirements, would be nice if there will be a way to install and start semaphore with answer file.

**Comment by gcavalcante8808** [comment] 2016-11-10 11:59
@KarenTovmasian 
Do you have some 'sample' about the file? 

Actually I'm use the ansible to setUP the semaphore container... And then ... use the container.

**Comment by KarenTovmasian** [comment] 2016-11-10 12:50
@gcavalcante8808 
something like a YAML file
```yaml
---
db_host: 192.168.1.1
db_port: 3306 # 3306 by default if not provided
db_user: someuser # semaphore by default if not provided
db_password: supersecurepassword
```
etc.

Docker is nice, but we don't plan to use it yet.

**Comment by gcavalcante8808** [comment] 2016-11-10 13:20
An playbook file ... I think this post is a duplicate of https://github.com/ansible-semaphore/semaphore/issues/194

We dont have it yet, but is not hard to work with.

**Comment by KarenTovmasian** [comment] 2016-11-10 13:27
@gcavalcante8808 it hasn't to be exactly playbook, it can be a JSON or whatever. The idea is that i write the file and then execute
```bash
semaphore -setup -answer-file /path/to/answer/file
```

**Comment by gcavalcante8808** [comment] 2016-11-10 13:32
@KarenTovmasian Ah now I understood your question... Well at the docker container I use the following script at the container startup proccess:

https://raw.githubusercontent.com/gcavalcante8808/docker-semaphore/master/semaphore.sh

The following line does a similar job for what you want (I think):

/usr/bin/semaphore -setup < /tmp/config_opts

**Comment by matejkramny** [comment] 2016-11-17 20:18
@KarenTovmasian is it possible to supply the config json that semaphore would generate instead of the answer/yaml file?

**Comment by KarenTovmasian** [comment] 2016-11-18 11:52
@matejkramny actually i don't care if it's json or yaml or whatever. since it can't be reused to run automated install of semaphore - it's fine :)

**Comment by matejkramny** [comment] 2016-11-18 20:05
I'm not sure I follow @KarenTovmasian, you're provisioning a box with semaphore. The yaml file provided (3rd comment) is generated no?

You can generate the equivalent json file and put it in .. /etc/semaphore.json, then run the semaphore binary pointing to the file.

**Comment by gcavalcante8808** [comment] 2016-11-18 20:43
If you input a file with the answers it Works. Take a look at the script
linked in the previous answers:

The script have values per line that are congruent with the questions from
setup.

Em 18 de nov de 2016 6:05 PM, "Matej Kramny" <notifications@github.com>
escreveu:

**Comment by morbidick** [comment] 2017-04-17 12:54
Hi, its not very beautiful but im generating a default config and then merge it with the role vars https://github.com/morbidick/ansible-role-semaphore/blob/master/tasks/main.yml#L54-L83

**Comment by ndeixonne** [comment] 2017-06-12 18:14
If you use Ansible, you can use the module expect to handle this kind of behavior. Even if a complete ini file passed in parameter of semaphore -setup would be the best solution.
Expect can be hard to use as official documentation provides examples that don't work ^^'

Here is how you could use it : 
```
- name: configure semaphore
  expect:
    command: semaphore -setup
    echo: yes
    timeout: 10
    responses: 
        "> DB Hostname": 
          - ""
        "> DB User":
          - "root"
        [...]
```

it works like that : 
```
responses:
  "string in the question":
    - "response"
```
The string must be existing in the question. You don't have to write all the question as some people will make you believe.

**Comment by matejkramny** [comment] 2017-06-12 18:53
What if we change the wording in the next release?

The best way to install semaphore automatically is to generate a json config file that the `-setup` flag produces. The keys in that config file are version safe in the semver world.

**Comment by ndeixonne** [comment] 2017-06-12 19:00
I agree. The problem is that current Setup step does more that the current json configuration file generated. It configures email alert, the admin account etc... Creating the first admin account is vital since otherwise you have no way to connect to Semaphore.

**Comment by matejkramny** [comment] 2017-06-12 19:02
I see. Then we must add command line utilities to aid automated setups.

**Comment by fiftin** [comment] 2022-01-27 16:55
You can add new account using command:

```
semaphore user add --config ./config.json --admin --login admin --email admin@example.com --name Admin --password 12345
```

Fore more info use command or [docs](https://docs.ansible-semaphore.com):

```
semaphore --help
```

**Closed by fiftin** 2022-01-27 16:55 UTC
Labels: proof of concept
