### ISSUE TITLE
Wrong SSH key is used by Task Template.

### ISSUE THREAD

**Issue by kinghrothgar** [ansible-semaphore/semaphore#398] opened 2017-07-19 15:58 UTC
I'm not sure if I'm encountering a bug or there's some misconfiguration. I have a key I will call key1. This is the first key I added. This is used to pull the repository. I then added key2 and created a task template set to use key2 as the SSH key. When I run the task, it fails to log into the target host with permission denied, and the debug info shows that it is using a file called access_key_1.  I checked access_key_1  and it contains key1, not the correct key2.  I ran this while running the task to see if it was at anytime the correct key and it was not:

```
while true; do grep "LAST_FEW_KEY_CHARS" access_key_1; done
```

I am using v2.4.1. I have checked in mysql and the correct key is stored for key2

I believe this output shows the wrong key being installed:

```
12:07:43: Started: 17
12:07:43: Run task with template: react web staging

12:07:43: access key key1 installed
12:07:43: Updating repository REDACTED
12:07:43: From REDACTED
12:07:43:  * branch            master     -> FETCH_HEAD
12:07:43: Already up-to-date.
12:07:43: access key key1 installed
12:07:43: installing static inventory
12:07:43: Using /home/semaphore/repository_1/ansible.cfg as config file
```

After more debugging and reading through the source it seems that inventory SSH key is used. As far as I can tell, the task template SSH key isn't used anywhere. This is very confusing.

**Comment by strangeman** [comment] 2017-07-19 23:24
Can you check table `project__template` in MySQL to ensure what key is used in the template (`ssh_key_id` column)?

**Comment by gcavalcante8808** [comment] 2018-01-19 13:51
@strangeman Can this be related to the requirement to have the keys installed inside .ssh folder?

I have an https://hub.docker.com/r/gcavalcante8808/semaphore/ image and since 'ever' the key should be installed as well in the .ssh folder.

**Comment by twhiston** [comment] 2018-02-19 20:15
cannot reproduce so closing due to age

**Closed by twhiston** 2018-02-19 20:15 UTC
