### ISSUE TITLE
Missing Author name in Slack Alert

### ISSUE THREAD

**Issue by prakyathraj** [ansible-semaphore/semaphore#1931] opened 2024-04-12 12:21 UTC
Using Slack alerts to get notification on task completion. Getting alerts as expected but it is missing the Author name. 

Configuration: I use Google OAuth for user creation, so username/author is supposed to be my office email address. 

Screenshot of alert in Slack:
![Screenshot 2024-04-12 at 5 49 42 PM](https://github.com/semaphoreui/semaphore/assets/159525040/493be6a4-c781-4a64-a4cf-c30347826b46)

**Comment by tboerger** [comment] 2024-04-12 14:03
Duplicate of https://github.com/semaphoreui/semaphore/issues/1870

**Closed as completed by tboerger** 2024-04-12 14:03 UTC

**Comment by prakyathr** [comment] 2024-04-12 14:14
@tboerger I checked the #1870 PR and it does not seem to fix the issue I faced because in my case above, I ran the tasks manually, not via cron but alert still not showing Author name.

**Comment by tboerger** [comment] 2024-04-13 19:21
Will be fixed with #1933
