### ISSUE TITLE
Problem: semaphore_2.10.32 appears to break synchronize:

### ISSUE THREAD

**Issue by macau23** [ansible-semaphore/semaphore#2481] opened 2024-10-22 19:45 UTC
### Issue

Problem with semaphore_2.10.32_linux_amd64.rpm
Worked with semaphore_2.10.22_linux_amd64.rpm
Also works with semaphore_2.10.31_linux_amd64.rpm

`fatal: [dev-X]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"rsync\" in paths: :/sbin:/usr/sbin:/usr/local/sbin"}`

while using ansible module synchronize: 

### Impact

Ansible (task execution)

### Installation method

Package

### Database

MySQL

### Semaphore Version

2.10.32

**Comment by Omicron7** [comment] 2024-10-22 19:55
This is a duplicate of https://github.com/semaphoreui/semaphore/issues/2464
`PATH` is no longer exposed in the ENV vars, so the shell has no idea where to find `rsync`.

**Comment by macau23** [comment] 2024-10-22 20:35
It is under /usr/bin/rsync (also /bin/rsync, https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin)

This is a breaking change - could it be made in a major version?

**Comment by macau23** [comment] 2024-10-23 08:17
> This is a duplicate of #2464

**Closed as not planned** 2024-10-23 09:10 UTC
