### ISSUE TITLE
SSH connecting with wrong username in 2.9.70

### ISSUE THREAD

**Issue by guyke01** [ansible-semaphore/semaphore#1964] opened 2024-04-22 12:19 UTC
With version 2.9.70 there seems to be a issue with connection to hosts over SSH. I'm using a SSH key with the defined username but Semaphore is connecting to machines with the username semaphore@x.x.x.x

I've updated the SSH key and username that is stored in the keystore, but it keeps using the semaphore username. This issue is since i've installed v2.9.70.

**Comment by photoncody** [comment] 2024-04-23 02:28
I am also having this issue. I'm rolling back my version of semaphore to see if that fixes the issue or not.

**Comment by photoncody** [comment] 2024-04-23 02:31
Confirmed. Rolling back to v2.9.64, this issue is resolved.

**Comment by neocult-de** [comment] 2024-04-23 16:18
Can confirm the issue. Since the update to v2.9.70. I dont get the same issue for all servers. But there seem to be a parsing error in parsing the values to pass to the command line. I have attached the error but masked SERVERNAME and USERNAME which be the normal login and name of the remote server. (Rolling back to v2.9.64 the issue does not occur)

Couldn´t make out a pattern which servers have a parsing error or not.

`fatal: [SERVERNAME]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo Please login as the user \"USERNAME\" rather than the user \"root\"./.ansible/tmp `\"&& mkdir \"` echo Please login as the user \"USERNAME\" rather than the user \"root\"./.ansible/tmp/ansible-tmp-1713888161.0375252-1432-86717521816157 `\" && echo ansible-tmp-1713888161.0375252-1432-86717521816157=\"` echo Please login as the user \"USERNAME\" rather than the user \"root\"./.ansible/tmp/ansible-tmp-1713888161.0375252-1432-86717521816157 `\" ), exited with result 142, stdout output: Please login as the user \"USERNAME\" rather than the user \"root\".\n\n", "unreachable": true}`

**Comment by fiftin** [comment] 2024-04-29 05:38
Hi @guyke01 fixed in 2.9.75. Thank you!

**Closed as completed by fiftin** 2024-04-29 05:38 UTC
Labels: bug, critical

**Comment by guyke01** [comment] 2024-04-29 05:46
Thanks @fiftin! Tested it yesterday and it works again!
