### ISSUE TITLE
v2.9.56 breaks oidc auth with keycloak

### ISSUE THREAD

**Issue by rsch136** [ansible-semaphore/semaphore#1864] opened 2024-03-24 18:18 UTC
When updating from [v2.9.45](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.9.45) to [v2.9.56](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.9.56), our existing integration with keycloak breaks. 

The error shown in the docker logs is `time="2024-03-24T17:38:23Z" level=error msg="oauth2: \"invalid_grant\" \"Code not valid\""`. On the UI side, signing in with SSO just returns you to the login page but does not actually log the user in.

A downgrade to 2.9.45 fixes the issue.

**Comment by fiftin** [comment] 2024-03-24 18:47
Hi @rsch136 , thanks a lot

**Comment by fiftin** [comment] 2024-03-24 19:16
@rsch136 Could you provide your provider configuration (without secrets), I need it to reproduce the issue?

@tboerger can you help? :)

**Comment by fiftin** [comment] 2024-03-24 19:24
@rsch136 configuration which works for me:
```json
"keycloak": {
	"display_name":"Sign in with keycloak",
	"provider_url":"http://localhost:8080/realms/master",
	"client_id":"test",
	"client_secret":"A0G8Awc7NTHrfllbXABbNK9kRQgQq7X9",
	"redirect_url": "http://localhost:8082/api/auth/oidc/keycloak/redirect"
}
```

**Comment by fiftin** [comment] 2024-03-24 19:28
I found this by the issue: https://keycloak.discourse.group/t/getting-invalid-grant-during-client-token-request-using-authorization-code/2042/4

@rsch136 
I need more info about your configuration. Do you have query string (`/redirect?query_sting`) in your `redirect_url`?

**Comment by rsch136** [comment] 2024-03-24 19:47
This is our config:
``` JSON
{
"web_host": "https://semaphore......de",
  "oidc_providers": {
    "keycloak": {  
      "display_name": "SSO",
      "provider_url": "https://keycloak.../realms/network",
      "client_id": "semaphore",
      "client_secret": "{{ semaphore_keycloak_client_secret }}"
      }
  }
}
```
We do not specify a redirect url here.

**Comment by fiftin** [comment] 2024-03-25 00:33
@rsch136 where you specify redirect_url? I have following error without it:

<img width="564" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/914224/ed6c27ef-09dc-4bd8-a00a-aab737f2a592">

**Comment by bodzio4749** [comment] 2024-03-25 06:13
Actually, 2.9.56 breaks much more. After the upgrade I got meself a surprise page  too. Granted I am running inside the docker.

![Screenshot 2024-03-24 225718](https://github.com/ansible-semaphore/semaphore/assets/47053642/a86225cc-8c55-4db2-9031-963e1cdfca43)

it was caused (I am guessing here) by my attempt to downgrade to 2.9.45 . There reason of this downgrade attempt was an 
error in running my simple ansible job of pining some servers, which worked fine up till now. The error message in the task log 
indicates problems with ... ssh-agent having problems reading socks (I wonder who game them under the Christmas tree).  Here is the following screen snapshot.

![Screenshot 2024-03-24 230444](https://github.com/ansible-semaphore/semaphore/assets/47053642/31fb26be-14fd-43cd-b5e3-147f889111f3)

SSH-AGENT is responsible for feeding passphrase when a SSH private key is pass protected. I am not using such protection for Semaphore. I created a special set of keys to and distributed them to all servers to avoid the problem. 
I hope this helps. In the meantime, back to the last night snapshot for recovery.

**Comment by fiftin** [comment] 2024-03-25 11:06
@bodzio4749 please create separate issue for your problem with details. Because I don't see whole error log.

PS: SSH-AGENT used in Semaphore starts form v2.9.45. There is no changes for this in v2.9.58.

**Comment by fiftin** [comment] 2024-03-25 11:11
@bodzio4749 do you have issue with OpenID connect?

**Comment by fiftin** [comment] 2024-03-25 11:11
@bodzio4749 do you have issue with OpenID connect?

**Comment by rsch136** [comment] 2024-03-25 12:21
> @rsch136 where you specify redirect_url? I have following error without it:
> 
> <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/914224/316355404-ed6c27ef-09dc-4bd8-a00a-aab737f2a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjg2OTksIm5iZiI6MTcxMTM2ODM5OSwicGF0aCI6Ii85MTQyMjQvMzE2MzU1NDA0LWVkNmMyN2VmLTA5ZGMtNGJkOC1hMDBhLWFhYjczN2YyYTU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMjA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWYwZDIxMGMxMDExNDAzYjYzYWE5MjQ4ZjVjZmQ1MjNkODc4MmRmMWEyMjY3YjVmM2Q4MGNmZjAzODA1YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LAO0muGq7yzSwTPbsiJSc_QUhVRR_U_yGpBSfzx5mhg">

Which version of keycloak are you using? I remember having this kind of issue when switching between keycloak version 14 and 19. We're currently using 19.0.3. 

I'm not specifying any redirect url. I will deploy it later tonight with an explicit redirect url in the config.

**Comment by fiftin** [comment] 2024-03-25 12:28
@rsch136 can we contact via Telegram? It is critical bug and I want to fix is ASAP. https://t.me/semaphoreui. Thank you

**Comment by mhzawadi** [comment] 2024-03-25 17:00
FYI: 2.9.56 with Kycloak 24.0.1 is working fine, can provide any configs you need

**Comment by mhzawadi** [comment] 2024-03-25 17:02
@bodzio4749 when you get that error, just re-login

**Comment by rsch136** [comment] 2024-03-25 18:47
I've deployed it again with a redirect url and latest version but it does not fix the error. I guess it could now be a problem with our version of keycloak. Unfortunately, I will not be able to update that anytime soon.

> FYI: 2.9.56 with Kycloak 24.0.1 is working fine, can provide any configs you need

@mhzawadi yes, please

@fiftin Since I am the only one who seems to be having this problem, I would be ok with closing the issue. I can open a new one if it still doesn't work once I've updated keycloak.

**Comment by fiftin** [comment] 2024-03-25 19:51
Please don't close the issue :)

**Comment by bodzio4749** [comment] 2024-03-25 20:11
@mhzawadi, @fiftin - yes, regular login with user and password.  No OpenId.

**Comment by jsievertde** [comment] 2024-03-26 15:35
Hmm everything over v2.9.45 seems to also break oidc with authentik as IDP.
Here is the relevant part of our `config.json`
```
"oidc_providers": {
        "XXX": {
            "display_name": "Authentik",
            "provider_url": "https://authentik.XXX.de/application/o/XXX/",
            "client_id": "XXX",
            "client_secret": "XXX",
            "redirect_url": "https://automation.XXX.de/api/auth/oidc/XXX/redirect/",
            "scopes": ["openid", "profile", "email"],
            "username_claim": "preferred_username",
            "name_claim": "preferred_username"
            }
        },
```

**Comment by mhzawadi** [comment] 2024-03-27 07:56
> @mhzawadi, @fiftin - yes, regular login with user and password. No OpenId.

My semaphore config below, then screen grabs of Keycloak. let me know if you need anything else
```
   "oidc_providers":{
      "horwood":{
         "display_name":"Sign in with keycloak",
         "provider_url":"https://keycloak/realms/PVE01",
         "client_id":"semaphore-real",
         "client_secret":"SECRETKEY",
         "redirect_url": "https://semaphore/api/auth/oidc/horwood/redirect"
      }
   },
```

<img width="757" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/11944327/ec2b34cd-dce1-42e4-98a0-c595966de434">

<img width="585" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/11944327/a1a82bab-1926-42a5-ae05-9e1e40f09195">


<img width="1136" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/11944327/14111a5f-5e2b-4625-b1e2-a79e2ab1115d">

**Comment by fiftin** [comment] 2024-03-27 13:59
@mhzawadi it doesn't work for 2.9.58, but works for 2.9.45?

Could you provide error log?

**Comment by fiftin** [comment] 2024-03-27 14:01
@jsievertde could you provide error log?

**Comment by ghost** [comment] 2024-03-27 14:10
also an issue with using Okta and using the latest docker image. happy to provide more info as needed

error log:

```
time="2024-03-27T14:06:34Z" level=error msg="oauth2: \"invalid_grant\" \"The authorization code is invalid or has expired.\""
```

configuration:

```json
    "oidc_providers": {
        "okta": {
            "display_name": "Sign in with Okta",
            "provider_url": "https://11111111.okta.com/oauth2/default",
            "client_id": "SOME_CLIENT_ID",
            "client_secret": "SOME_CLIENT_SECRET",
	    "name_claim": "name"
        }
    }
```

**Comment by fiftin** [comment] 2024-03-27 15:51
@pushpinders1ngh just created Okta acc. Works to me. Can't reproduced.

Okta has a log. Can you share it?

<img width="1037" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/914224/55c096fd-da44-499a-a81a-4976ccbe0606">

**Comment by fiftin** [comment] 2024-03-27 16:10
@jsievertde please share the logs.

**Comment by ghost** [comment] 2024-03-27 16:20
@fiftin all successful logins

<img width="1007" alt="image" src="https://github.com/ansible-semaphore/semaphore/assets/146976116/383bc215-30c1-405c-b4d3-f5adc5bab146">

**Comment by fiftin** [comment] 2024-03-27 17:30
Please try [v2.9.64](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.9.64).

**Comment by ghost** [comment] 2024-03-27 18:02
Unfortunately, the same result with v2.9.64.

**Comment by rsch136** [comment] 2024-03-27 18:09
I'm also getting the same result but there is an extra error now: **http: panic serving 172.18.0.4:50116: securecookie: hash key is not set**

```
time="2024-03-27T17:58:22Z" level=error msg="oauth2: \"invalid_grant\" \"Code not valid\""
2024/03/27 17:59:35 http: panic serving 172.18.0.4:50116: securecookie: hash key is not set
goroutine 71 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0xbfd580?, 0xc0001a9b00?})
        /usr/local/go/src/runtime/panic.go:920 +0x270github.com/ansible-semaphore/semaphore/api.createSession({0x1e6ce60, 0xc000546000}, 0xc0004fa200, {0x1, {0x0, 0xedd926561, 0x0}, {0xc00040e340, 0x1d}, {0xc000013478, ...}, ...})
        /go/src/github.com/ansible-semaphore/semaphore/api/login.go:151 +0x491github.com/ansible-semaphore/semaphore/api.oidcRedirect({0x1e6ce60, 0xc000546000}, 0xc0004fa200)
        /go/src/github.com/ansible-semaphore/semaphore/api/login.go:655 +0x9d0
net/http.HandlerFunc.ServeHTTP(0xbdc5e0?, {0x1e6ce60?, 0xc000546000?}, 0xc?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/ansible-semaphore/semaphore/api.JSONMiddleware.func1({0x1e6ce60, 0xc000546000}, 0x45442b?)
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:44 +0xf6
net/http.HandlerFunc.ServeHTTP(0xb2de00?, {0x1e6ce60?, 0xc000546000?}, 0x774e8c?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1.1()
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:35 +0x28github.com/ansible-semaphore/semaphore/db.StoreSession({0x1e791f0, 0xc0000666a0}, {0xc0002d42e0, 0xc}, 0xc00059f7b8)
        /go/src/github.com/ansible-semaphore/semaphore/db/Store.go:432 +0x5fgithub.com/ansible-semaphore/semaphore/api.StoreMiddleware.func1({0x1e6ce60?, 0xc000546000}, 0xc0004fa200)
        /go/src/github.com/ansible-semaphore/semaphore/api/router.go:34 +0xf5
net/http.HandlerFunc.ServeHTTP(0xc0004fa200?, {0x1e6ce60?, 0xc000546000?}, 0xbe6f80?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/ansible-semaphore/semaphore/cli/cmd.runService.func1.1({0x1e6ce60, 0xc000546000}, 0xc0002121e0?)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:74 +0xea
net/http.HandlerFunc.ServeHTTP(0xc000600000?, {0x1e6ce60?, 0xc000546000?}, 0xc00059f8e8?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/ansible-semaphore/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x1e6ce60, 0xc000546000}, 0xc0002120f0?)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x88
net/http.HandlerFunc.ServeHTTP(0xc0004fa100?, {0x1e6ce60?, 0xc000546000?}, 0xc00059f990?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x1e6ce60, 0xc000546000}, 0xc0004fa000)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1c5github.com/ansible-semaphore/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x1e6ce60, 0xc000546000}, 0xc0004fa000)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x143
net/http.HandlerFunc.ServeHTTP(0xc000180104?, {0x1e6ce60?, 0xc000546000?}, 0x444140?)
        /usr/local/go/src/net/http/server.go:2136 +0x29github.com/ansible-semaphore/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x1e6ce60, 0xc000546000}, 0xc0004fa000)
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:27 +0xbd
net/http.HandlerFunc.ServeHTTP(0x235f100?, {0x1e6ce60?, 0xc000546000?}, 0xc00059fb50?)
        /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0xc0004ba930?}, {0x1e6ce60?, 0xc000546000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000126090, {0x1e6ec58, 0xc0004ba810})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
time="2024-03-27T17:59:35Z" level=error msg="oauth2: \"invalid_grant\" \"Code not valid\""
```

I've also changed the set-up in keycloak like recommended here: https://github.com/ansible-semaphore/semaphore/issues/1864#issuecomment-2022152761
But this did not change anything with v2.9.56. I assume it also has no affect on v.2.9.64

**Comment by fiftin** [comment] 2024-03-27 18:09
@pushpinders1ngh please add `"redirect_url": "https://semaphore/api/auth/oidc/okta/redirect"` to your config file.

**Comment by fiftin** [comment] 2024-03-27 18:14
@rsch136 looks like you have broken config. Please check that you have `cookie_hash` in your config file or `SEMAPHORE_COOKIE_HASH` environment variable. It must be generated by command `head -c32 /dev/urandom | base64`.

**Comment by rsch136** [comment] 2024-03-27 18:48
> @rsch136 looks like you have broken config. Please check that you have `cookie_hash` in your config file or `SEMAPHORE_COOKIE_HASH` environment variable. It must be generated by command `head -c32 /dev/urandom | base64`.

@fiftin we were following this docu: https://docs.semui.co/administration-guide/openid

Didn't previously have any issue with cookie hashes. Do you have a link?

**Comment by ghost** [comment] 2024-03-27 18:58
Thank you @fiftin. Very generous of you to provide this quick solution. adding the `redirect_url` fixed it. Just curious how is it different from omitting the `redirect_url` and letting it use the default as suggested in the doc: `${web_host}/api/auth/oidc/${provider}/redirect`, shouldn't this expand to the same value as long as web_host is defined correctly? did the behaviour of the default values changed in the newer versions?

i've in my config: 
`web_host: https://semaphore.example.com`
`redirect_url: https://semaphore.example.com/api/auth/oidc/okta/redirect`

**Comment by fiftin** [comment] 2024-03-27 19:19
@pushpinders1ngh I can't understand how it worked in 2.9.45. I tested with it and got error "invalid redirect_url".

**Comment by fiftin** [comment] 2024-03-27 19:21
> ${web_host}/api/auth/oidc/${provider}/redirect

@phishkapsch Hm, it is really strange

**Comment by mhzawadi** [comment] 2024-03-27 20:31
I have updated to 2.9.65 and all is working fine for me

**Comment by jsievertde** [comment] 2024-03-28 14:16
@fiftin sorry for the delay. I copied the relevant error from our authentik-backend:
```
{
    "message": "Invalid redirect URI used by provider",
    "expected": [
        "https://automation.XXX.de/api/auth/oidc/XXX-authentik/redirect/"
    ],
    "provider": {
        "pk": 7,
        "app": "authentik_providers_oauth2",
        "name": "automation.XXX.de",
        "model_name": "oauth2provider"
    },
    "http_request": {
        "args": {},
        "path": "/application/o/token/",
        "method": "POST",
        "user_agent": "Go-http-client/2.0"
    },
    "redirect_uri": "https://automation.XXX.de/api/auth/oidc/XXX-authentik/redirect//api/auth/oidc/XXX-authentik/redirect"
}
User
{
    "pk": 1,
    "email": "",
    "username": "AnonymousUser",
    "is_anonymous": true
}
```
I'm just deploying the new version of ansible-semaphore to check if it is already fixed.

**Comment by fiftin** [comment] 2024-03-28 14:41
Hi @jsievertde It is what I fixed in 2.9.64. Didn't help?

**Comment by jsievertde** [comment] 2024-03-28 14:47
Sorry @fiftin deployment is done and the service has been restarted.
It's also fixed now for us.
Thanks for your work.

**Comment by rsch136** [comment] 2024-04-01 15:39
Adding the cookie_hash to the env fixed the issue and I can now sign in using keycloak. I updated keycloak to 24.0.0 before adding the cookie_hash but this did not change anything. It also works without adding the redirect url to the config.

Thanks for the help!

**Closed as completed** 2024-04-02 15:31 UTC
Labels: bug, critical

**Comment by hmoffatt** [comment] 2024-07-18 04:31
I just upgraded from an old version to the latest and encountered this. I did not have a `redirect_url` set before but had to add one now.
