### ISSUE TITLE
Basic Install Doesn't Seem to Work

### ISSUE THREAD

**Issue by chaseconey** [ansible-semaphore/semaphore#6] opened 2015-03-11 00:24 UTC
Just ran through the quickstart installation and it doesn't appear to be working...

Version information:
**OS:** OSX 10.10.2 (newest)
**vagrant:** 1.7.2

`vagrant up` runs perfectly fine, all steps are run with no issues but http://localhost:3000 doesn't serve up anything. What are some steps to figure out what is going on here?

Thanks

**Comment by leopoul** [comment] 2015-03-11 10:04
Run into the same issue. From the latest commit's description "Fix authentication failures & get rid of grunt" it seems that grunt is been taken off. So, I guess this no longer works https://github.com/ansible-semaphore/semaphore/blob/master/playbooks/run_semaphore#L4 and it should go via node.
After failing I went with vagrant ssh and flowed the steps of README:

1. `cp lib/credentials.example.json lib/credentials.json` (<- make custom to your environment)
2. `bower install`
3. `node bin/semaphore`

(2) is probably not needed.

However now I get a:
```
GET /vendor/requirejs/require.js 200 15.882 ms - 764
  LESS File error : '../vendor/fontawesome/less/font-awesome.less' wasn't found. Tried - /opt/semaphore/public/vendor/fontawesome/less/font-awesome.less,../vendor/fontawesome/less/font-awesome.less
  LESS File : /opt/semaphore/public/css/semaphore.less 13:0
Error: '../vendor/fontawesome/less/font-awesome.less' wasn't found. Tried - /opt/semaphore/public/vendor/fontawesome/less/font-awesome.less,../vendor/fontawesome/less/font-awesome.less
```
whenever I hit localhost:3000 from my host

**Comment by craftbyte** [comment] 2015-03-11 10:11
It seems like the issue is that the vendor folder doesn’t exist. Seems like the dependencies are not in there.

**Comment by leopoul** [comment] 2015-03-11 12:03
Got it working eventually.
Step 2 is needed `bower install` 
However, running the above I got:
`bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128`

Googling around, I fixed the prob with:
```
git config --global url."https://".insteadOf git://
bower cache clean
bower install --allow-root
```

My semaphore is up. It definitely needs some looking into. If I find time I'll try to send a patch

**Comment by matejkramny** [comment] 2015-03-11 12:15
Yep the work aligns with #5.

**Comment by matejkramny** [comment] 2015-03-27 10:57
Should've been closed when #11 got merged. Strange GH didn't.

**Closed by matejkramny** 2015-03-27 10:57 UTC
