### ISSUE TITLE
Console window view not updating

### ISSUE THREAD

**Issue by d11ahirst** [ansible-semaphore/semaphore#1754] opened 2024-02-09 17:50 UTC
The console window does not update when running a task created by another user.

Reproduction steps:

1. Login as User A
2. Create an extra account called User B
3. Create a task with User A
4. Logout
5. Login With User B
6. Run the task created by User A
7. Watch the console view not updating

**Comment by d11ahirst** [comment] 2024-02-12 12:09
Just to add to this bug, this make using semaphore and auditing trail a bit of a problem as we need to track who ran the jobs

**Comment by robinmalik** [comment] 2024-02-23 15:10
I have issues with the interface not updating in a slightly different way - if I run a task the console window updates just fine, but closing that doesn't result in the main page refreshing. I actually have to F5 in order to see the latest task run appear.

**Comment by jb137** [comment] 2024-03-31 10:55
Please check if user B is a member of the team and not just an admin user.

**Comment by fiftin** [comment] 2024-04-02 15:08
Hi @d11ahirst I can't reproduce your issue. Do you use NGINX or Apache with Semphore? It can be reverse proxy config issue.

> Just to add to this bug, this make using semaphore and auditing trail a bit of a problem as we need to track who ran the jobs

It works like you said.

**Comment by fiftin** [comment] 2024-04-02 15:10
I'm closing the issue. Will reopen the issue if anyone else has the same problem.

**Comment by robinmalik** [comment] 2024-04-02 15:12
@fiftin I'm using NGINX. Running as admin. Would you prefer I open a separate issue?

**Comment by fiftin** [comment] 2024-04-02 21:24
I reproduced the issue

**Closed as completed** 2024-04-02 22:23 UTC
Labels: bug
